apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: github-tests-go-hyqtlfib
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: github-tests-go-hyqtlfib 
  name: github-tests-go-hyqtlfib
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: github-tests-go-hyqtlfib 
